openapi: 3.0.1
info:
  title: ServerInfo
  description: API Definition of ServerInfo
  version: 1.0.0
servers:
- url: http://localhost:8290/serverinfo
paths:
  /:
    get:
      responses:
        default:
          description: Default response
